stages:
  prepare_data:
    cmd: python prepare_data.py
    deps:
      - data/cancer_reg1.csv
      - params.yaml
    params:
      - general
      - preprocessing
    outs:
      - data/prepared_data.pkl
      - plots/full_correlation.png
      - models/features.json
      - models/scaler.pkl

  train_linear_regression:
    cmd: python train_linear_regression.py
    deps:
      - data/prepared_data.pkl
      - src/linear_regression.py
      - params.yaml
    params:
      - linear_regression
    outs:
      - models/linear_regression.pkl
      - metrics/linear_regression_equation.txt
    metrics:
      - metrics/linear_regression_metrics.json

  train_decision_tree:
    cmd: python train_decision_tree.py
    deps:
      - data/prepared_data.pkl
      - src/decision_tree.py
      - params.yaml
    params:
      - decision_tree
    outs:
      - models/decision_tree.pkl
      - plots/decision_tree.png
    metrics:
      - metrics/decision_tree_metrics.json

  train_catboost:
    cmd: python train_catboost.py
    deps:
      - data/prepared_data.pkl
      - src/catboost_model.py
      - params.yaml
    params:
      - catboost
    outs:
      - models/catboost.cbm
    metrics:
      - metrics/catboost_metrics.json

  train_xgboost:
    cmd: python train_xgboost.py
    deps:
      - data/prepared_data.pkl
      - src/xgboost_model.py
      - params.yaml
    params:
      - xgboost
    outs:
      - models/xgboost.json
    metrics:
      - metrics/xgboost_metrics.json

  train_neural_network:
    cmd: python train_neural_network.py
    deps:
      - data/prepared_data.pkl
      - src/neural_network.py
      - params.yaml
    params:
      - neural_network
    outs:
      - models/neural_network.keras
    metrics:
      - metrics/neural_network_metrics.json

  compare_models:
    cmd: python compare_models.py
    deps:
      - metrics/linear_regression_metrics.json
      - metrics/decision_tree_metrics.json
      - metrics/catboost_metrics.json
      - metrics/xgboost_metrics.json
      - metrics/neural_network_metrics.json
    outs:
      - metrics/models_comparison.json
      - metrics/models_comparison.csv


plots:
  - metrics/linear_regression_plot_data.csv:
      x: dataset
      y: R2
      title: Linear Regression R²
  - metrics/decision_tree_plot_data.csv:
      x: dataset
      y: R2
      title: Decision Tree R²
  - metrics/catboost_plot_data.csv:
      x: dataset
      y: R2
      title: CatBoost R²
  - metrics/xgboost_plot_data.csv:
      x: dataset
      y: R2
      title: XGBoost R²
  - metrics/neural_network_plot_data.csv:
      x: dataset
      y: R2
      title: Neural Network R²
  - metrics/models_comparison.json:
      x: Модель
      y: R²_test
      title: Сравнение R² на тесте