stages:
  train_all_models:
    cmd: python main.py
    deps:
      - data/cancer_reg1.csv
      - main.py
      - src/correlation_plots.py
      - src/linear_regression.py
      - src/decision_tree.py
      - src/catboost_model.py
      - src/xgboost_model.py
      - src/neural_network.py
      - src/utils.py
      - config/params.yaml
    outs:
      - models
      - plots
    metrics:
      - metrics/linear_regression_metrics.json
      - metrics/decision_tree_metrics.json
      - metrics/catboost_metrics.json
      - metrics/xgboost_metrics.json
      - metrics/neural_network_metrics.json
      - metrics/models_comparison.csv
    params:
      - general.random_state
      - general.train_size
      - general.val_size
      - general.test_size
      - general.correlation_threshold
      - linear_regression.fit_intercept
      - linear_regression.positive
      - decision_tree.max_depth
      - decision_tree.min_samples_split
      - decision_tree.min_samples_leaf
      - catboost.iterations
      - catboost.learning_rate
      - catboost.depth
      - catboost.l2_leaf_reg
      - xgboost.n_estimators
      - xgboost.learning_rate
      - xgboost.max_depth
      - xgboost.subsample
      - xgboost.colsample_bytree
      - xgboost.reg_alpha
      - xgboost.reg_lambda
      - neural_network.epochs
      - neural_network.batch_size
      - neural_network.learning_rate
      - neural_network.layer_1_neurons
      - neural_network.layer_2_neurons
      - neural_network.layer_3_neurons
      - neural_network.dropout_rate
      - neural_network.patience